### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [jonpe960/ufsm#1]
I would like to point out that an identifier like “[`__UFSM_H__`](https://github.com/jonpe960/ufsm/blob/0c455220d1df52baccecfdb73352314f3262f49b/src/ufsm.h#L10 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by jonpe960** [comment]
That's a good point, I haven't explicitly selected a code convention. I'll add this in the next release.
