### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [jonpe960/ufsm#2]
Would you like to replace [more defines for constant values](https://github.com/jonpe960/ufsm/blob/0c455220d1df52baccecfdb73352314f3262f49b/src/ufsm.h#L16 "UFSM_ERROR…") by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages "Description for the usage of enumerations") to stress their relationships?

**Comment by jonpe960** [comment]
Agreed, there is no reason for the error codes to be #defines
