### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [jonpe960/ufsm#3]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [parse_state](https://github.com/jonpe960/ufsm/blob/a970174a9efe0ddbc0c423c52eb88ea41142f65a/src/tools/ufsmimport.c#L170)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [main](https://github.com/jonpe960/ufsm/blob/a970174a9efe0ddbc0c423c52eb88ea41142f65a/src/tools/ufsmimport.c#L614)

**Comment by jonpe960** [comment]
Yes, that's a good idea
