### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [jonpe960/ufsm#4]
I suggest to reuse a higher level build system than [your current make scripts](https://github.com/jonpe960/ufsm/blob/58b0b54b4697f8750f8cf26037f080f21b4bb8c4/Makefile#L2 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by jonpe960** [comment]
The actual library has no dependecies. The import tool uses libxml, which is the only dependency. It's not at good idea to introduce so much additional complexity for one dependency.

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.11/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?
